<?php
/**
 * @file
 * Code for the VP Alternative frontpage feature.
 */

include_once 'vp_alternative_frontpage.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * types of plugins: layouts, styles, args, contexts, content_types.
 */
function vp_alternative_frontpage_ctools_plugin_directory($owner, $plugin_type) {
  // We're just providing layout plugins.
  if ($owner == 'panels' && $plugin_type == 'layouts') {
    // panels_extra_layouts_ctools_plugin_directory.
    return "plugins/$plugin_type";
  }
}

function vp_alternative_frontpage_block_info() {
  $blocks['vp_alt_frontp_important_topics'] = array(
    'info' => t('VP alternative frontpage: Important topics'),
  );

  $blocks['vp_alt_frontp_direct_links'] = array(
    'info' => t('VP alternative frontpage: Direct links'),
  );

  return $blocks;
}


function vp_alternative_frontpage_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'vp_alt_frontp_important_topics':
      $block['subject'] = t('Important topics');
      $block['content'] = variable_get('vp_alt_frontp_important_topics_body', _vp_alternative_frontpage_block_templates($delta));
      break;

    case 'vp_alt_frontp_direct_links':
      $block['subject'] = t('Important topics');
      $block['content'] = variable_get('vp_alt_frontp_important_topics_body', _vp_alternative_frontpage_block_templates($delta));
      break;
  }

  return $block;
}

/**
 * Implements hook_block_configure().
 */
function vp_alternative_frontpage_block_configure($delta='') {
  $form = array();

  switch ($delta) {
    case 'vp_alt_frontp_important_topics':
      $form['vp_alt_frontp_important_topics_body'] = array(
        '#type' => 'text_format',
        '#title' => t('Enter your text here in WYSIWYG format'),
        '#default_value' => variable_get('vp_alt_frontp_important_topics_body', _vp_alternative_frontpage_block_templates($delta)),
      );
      break;

    case 'vp_alt_frontp_direct_links':
      $form['vp_alt_frontp_direct_links_body'] = array(
        '#type' => 'text_format',
        '#title' => t('Enter your text here in WYSIWYG format'),
        '#default_value' => variable_get('vp_alt_frontp_direct_links_body', _vp_alternative_frontpage_block_templates($delta)),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function vp_alternative_frontpage_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'vp_alt_frontp_important_topics':
      variable_set('vp_alt_frontp_important_topics_body', $edit['vp_alt_frontp_important_topics_body']['value']);
      break;

    case 'vp_alt_frontp_direct_links':
      variable_set('vp_alt_frontp_direct_links_body', $edit['vp_alt_frontp_direct_links_body']['value']);
      break;
  }
}

/**
 * Implements hook_theme().
 */
function vp_alternative_frontpage_theme() {
  $path = drupal_get_path('module', 'vp_alternative_frontpage');
  return array(
    'vp_alt_frontp_important_topics' => array(
      'template' => 'vp_alt_frontp_important_topics',
      'path' => $path . '/templates',
    ),
    'vp_alt_frontp_direct_links' => array(
      'template' => 'vp_alt_frontp_direct_links',
      'path' => $path . '/templates',
    ),
  );
}

/**
 * Helper function to get the default templates.
 *
 * @param string $delta
 * @return string
 */
function _vp_alternative_frontpage_block_templates($delta='') {
  $template = '';

  switch ($delta) {
    case 'vp_alt_frontp_important_topics':
      $default_template = theme('vp_alt_frontp_important_topics');

      if (variable_get('vp_alt_frontp_important_topics_body', '') === '') {
        $template = $default_template;
      }
      else {
        $template = variable_get('vp_alt_frontp_important_topics_body', '');
      }

      break;

    case 'vp_alt_frontp_direct_links':
      $default_template = '<p>new dynamisfsc content here sfsfdfsfsf33</p>';

      if (variable_get('vp_alt_frontp_direct_links_body', '') === '') {
        $template = $default_template;
      }
      else {
        $template = variable_get('vp_alt_frontp_direct_links_body', '');
      }
      break;
  }

  return $template;
}
