<?php
/**
 * @file
 * Code for the VP Wysiwyg template.
 */

/**
 * Implements hook_wysiwyg_plugin().
 */
function vp_wysiwyg_template_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'ckeditor':
      // We need to add the buttons to CKEditor for every widget so that
      // ACF (advanced content filter) would register them. Without the buttons,
      // ACF would strip all the html.
      drupal_add_css(drupal_get_path('module', 'vp_wysiwyg_template') . '/vp_wysiwyg_template.css');
      return array(
        'vp_hr' => array(
          'path' => drupal_get_path('module', 'vp_wysiwyg_template') . '/ckeditor/vp_hr',
          'buttons' => array(
            'vp_hr_button' => t('VP Widget: Horizontal Spacer'),
          ),
          'load' => TRUE,
        ),
        'vp_static_module_2' => array(
          'path' => drupal_get_path('module', 'vp_wysiwyg_template') . '/ckeditor/vp_static_module_2',
          'buttons' => array(
            'vp_static_module_2_button' => t('VP Widget: 2 Column (with VS in between)'),
          ),
          'load' => TRUE,
        ),
        'vp_static_simple_2columns' => array(
          'path' => drupal_get_path('module', 'vp_wysiwyg_template') . '/ckeditor/vp_static_simple_2columns',
          'buttons' => array(
            'vp_static_simple_2columns_button' => t('VP Widget: Simple 2 Columns'),
          ),
          'load' => TRUE,
        ),
        'vp_template_custom_gallery' => array(
          'path' => drupal_get_path('module', 'vp_wysiwyg_template') . '/ckeditor/vp_template_custom_gallery',
          'buttons' => array(
            'vp_template_custom_gallery_button' => t('VP Widget: Gallery'),
          ),
          'load' => TRUE,
        ),
        'vp_static_75_25_2columns' => array(
          'path' => drupal_get_path('module', 'vp_wysiwyg_template') . '/ckeditor/vp_static_75_25_2columns',
          'buttons' => array(
            'vp_static_75_25_2columns_button' => t('VP Widget: 75/25 columns with spacer'),
          ),
          'load' => TRUE,
        ),
      );
      break;


  }
}
