<?php
/**
 * @file
 * Code for the VP Wysiwyg template.
 */

/**
 * Implements hook_wysiwyg_plugin().
 */
function vp_wysiwyg_template_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'ckeditor':
      // We need to add the buttons to CKEditor for every widget so that
      // ACF (advanced content filter) would register them. Without the buttons,
      // ACF would strip all the html.
      drupal_add_css(drupal_get_path('module', 'vp_wysiwyg_template') . '/vp_wysiwyg_template.css');
      return array(
        'vp_static_75_25_2columns' => array(
          'path' => drupal_get_path('module', 'vp_wysiwyg_template') . '/ckeditor/vp_static_75_25_2columns',
          'buttons' => array(
            'vp_static_75_25_2columns_button' => t('VP Widget: 75/25 columns with spacer'),
          ),
          'load' => TRUE,
        ),
      );
      break;


  }
}
